version: '3.8'
services:
  db:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Arul
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: my-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: arul@arul.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"